# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd15826d89ecb0f28f36947a8014655e8cf891a45a68bc573717340943a749592eae60156ff144c712c2893fbb5a3d000650463c763139d0884eb3ef33108c89

test:
  secret_key_base: 2320bbaf02c1b6ef901b0b00c0bc5a32047705fd4ee145583b7349694d86e4052fc402edb61a8a2a163add65ef6e8223bac07918b1aa446add705dd0c8cd6659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
